// Atlas payments-service.
//
// Phase 4 scope (this commit):
//   - gRPC server on :50053 implementing atlas.payments.PaymentsService
//     (InitiateTransaction, SettleTransaction, GetWalletBalance,
//      RefundTransaction, DrainOutbox)
//   - grpc.health.v1.Health
//   - Wallet ledger + transactions (Exposed) with idempotency-key guard
//   - PaymentProvider abstraction (authorize/capture/refund); a fake provider
//     for local dev so Phase 4 stays at $0 spend
//   - Transactional outbox: every transaction state change writes a
//     protobuf FareEvent to payments.outbox in the SAME db tx, drained to
//     Kafka (atlas.fare.events) by a background dispatcher
//   - Ktor Netty HTTP server on :8053 serving /metrics (Micrometer/Prometheus)
//     and /webhooks/{provider} for async provider callbacks
//   - App.kt entry point + Dockerfile + shadow jar

import com.google.protobuf.gradle.id

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.protobuf)
    alias(libs.plugins.shadow)
    application
}

kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("io.atlas.payments.AppKt")
}

sourceSets {
    main {
        // Generated by protobuf-gradle-plugin under build/generated/source/proto/.
        java.srcDirs(
            "build/generated/source/proto/main/java",
            "build/generated/source/proto/main/grpc",
            "build/generated/source/proto/main/grpckt",
            "build/generated/source/proto/main/kotlin",
        )
        proto {
            // Pull .proto from the repo-root /proto directory (same approach as
            // auth-service) so the contract lives in exactly one place.
            srcDir("$rootDir/proto")
        }
    }
}

protobuf {
    protoc {
        artifact = libs.protoc.get().toString()
    }
    plugins {
        id("grpc") {
            artifact = libs.grpc.codegen.java.get().toString()
        }
        id("grpckt") {
            artifact = libs.grpc.codegen.kotlin.get().toString() + ":jdk8@jar"
        }
    }
    generateProtoTasks {
        all().forEach { task ->
            task.plugins {
                id("grpc") {}
                id("grpckt") {}
            }
            task.builtins {
                id("kotlin") {}
            }
        }
    }
}

dependencies {
    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation(libs.exposed.java.time)
    implementation(libs.hikari)
    implementation(libs.postgres)
    implementation(libs.slf4j.api)
    implementation(libs.logback.classic)
    implementation(libs.logstash.encoder)

    // gRPC + protobuf
    implementation(libs.grpc.stub)
    implementation(libs.grpc.protobuf)
    implementation(libs.grpc.netty.shaded)
    implementation(libs.grpc.services)
    implementation(libs.grpc.kotlin.stub)
    implementation(libs.protobuf.kotlin)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kafka.clients)

    // Ktor HTTP (metrics + provider webhooks) and Micrometer Prometheus
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    implementation(libs.ktor.server.content.negotiation)
    implementation(libs.ktor.serialization.jackson)
    implementation(libs.micrometer.registry.prometheus)

    testImplementation(libs.kotlin.test)
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.grpc.testing)
    testRuntimeOnly(libs.junit.platform.launcher)
}

tasks.shadowJar {
    archiveBaseName.set("payments-service")
    archiveClassifier.set("all")
    archiveVersion.set("")
    mergeServiceFiles()
}
