// Atlas auth-service.
//
// Phase 2A scope (done):
//   - Password hashing (bcrypt via jbcrypt)
//   - JWT signing and verification (HS256 via jose4j) with atlas:* claims
//   - User/session repositories (interface + in-memory + Exposed implementations)
//   - AuthService business logic: register, authenticate
//   - Unit tests
//
// Phase 2B scope (this commit):
//   - protoc + grpc-kotlin stub generation from repo-root proto/
//   - gRPC server on :50051 implementing atlas.auth.AuthService
//   - grpc.health.v1.Health
//   - 30s in-process token validation cache (Caffeine)
//   - Kafka producer for atlas.auth.tokens (protobuf-encoded AuthTokenEvent)
//   - Kafka consumer subscribed to its own topic for cache invalidation
//   - App.kt entry point + Dockerfile + shadow jar

import com.google.protobuf.gradle.id

plugins {
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.protobuf)
    alias(libs.plugins.shadow)
    application
}

kotlin {
    jvmToolchain(21)
}

application {
    mainClass.set("io.atlas.auth.AppKt")
}

sourceSets {
    main {
        // Generated by protobuf-gradle-plugin under build/generated/source/proto/.
        // Adding them to the main source set lets Kotlin code import the
        // generated classes (atlas.auth.AuthServiceGrpcKt, atlas.events.*).
        java.srcDirs(
            "build/generated/source/proto/main/java",
            "build/generated/source/proto/main/grpc",
            "build/generated/source/proto/main/grpckt",
            "build/generated/source/proto/main/kotlin",
        )
        proto {
            // Pull .proto files from the repo-root /proto directory rather than
            // copying or symlinking them into the module. Symlinks are fragile
            // on Windows and copies drift.
            srcDir("$rootDir/proto")
        }
    }
}

protobuf {
    protoc {
        artifact = libs.protoc.get().toString()
    }
    plugins {
        id("grpc") {
            artifact = libs.grpc.codegen.java.get().toString()
        }
        id("grpckt") {
            // The :jdk8@jar classifier is the published artifact name for the
            // grpc-kotlin code generator; the plugin pulls a JAR rather than
            // a native binary so it works on any host.
            artifact = libs.grpc.codegen.kotlin.get().toString() + ":jdk8@jar"
        }
    }
    generateProtoTasks {
        all().forEach { task ->
            task.plugins {
                id("grpc") {}
                id("grpckt") {}
            }
            task.builtins {
                id("kotlin") {}
            }
        }
    }
}

dependencies {
    // Phase 2A
    implementation(libs.exposed.core)
    implementation(libs.exposed.jdbc)
    implementation(libs.exposed.java.time)
    implementation(libs.hikari)
    implementation(libs.postgres)
    implementation(libs.jose4j)
    implementation(libs.jbcrypt)
    implementation(libs.slf4j.api)
    implementation(libs.logback.classic)
    implementation(libs.logstash.encoder)

    // Phase 2B
    implementation(libs.grpc.stub)
    implementation(libs.grpc.protobuf)
    implementation(libs.grpc.netty.shaded)
    implementation(libs.grpc.services)
    implementation(libs.grpc.kotlin.stub)
    implementation(libs.protobuf.kotlin)
    implementation(libs.kotlinx.coroutines.core)
    implementation(libs.kafka.clients)
    implementation(libs.caffeine)

    // Phase 8: /metrics. auth-service was the only service exposing no
    // metrics at all, on the busiest path in the platform.
    implementation(libs.ktor.server.core)
    implementation(libs.ktor.server.netty)
    implementation(libs.micrometer.registry.prometheus)

    testImplementation(libs.kotlin.test)
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.kotlinx.coroutines.test)
    testImplementation(libs.grpc.testing)
    testRuntimeOnly(libs.junit.platform.launcher)
}

// Shadow jar produces a single fat JAR the Dockerfile can run with
// `java -jar app.jar`. The shaded grpc-netty already includes its own copy of
// Netty, so we don't need extra relocations.
tasks.shadowJar {
    archiveBaseName.set("auth-service")
    archiveClassifier.set("all")
    archiveVersion.set("")
    mergeServiceFiles()
}
